In [1]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [3]:
df=pd.read_csv('cleaned_shipments.csv')

In [4]:
df.describe()

,transit_hours,distance_km,weight_kg,volume_m3,value_usd,freight_cost_usd,num_containers,num_stops,delay_hours,risk_score,weather_severity,port_congestion,priority_level,month,weekday,quarter
count,50000.000000,50000.000000,50000.000000,50000.000000,5.000000e+04,5.000000e+04,50000.000000,50000.000000,50000.000000,50000.000000,50000.000000,50000.000000,50000.000000,50000.000000,50000.000000,50000.000000
mean,274.375674,8979.712368,18447.085194,43.048501,4.203385e+05,1.761573e+04,12.493560,2.506500,5.529954,0.285463,0.199867,0.333096,2.506220,6.523560,2.991660,2.508180
std,210.443900,5981.398861,55060.017639,141.645794,1.867956e+06,8.473827e+04,6.914208,1.711787,15.416320,0.159034,0.136732,0.178151,1.118243,3.437749,2.001197,1.112042
min,12.000000,200.300000,1.000000,0.000000,1.000000e+02,5.700000e-01,1.000000,0.000000,0.000000,0.001300,0.000100,0.001700,1.000000,1.000000,0.000000,1.000000
25%,86.500000,3980.000000,770.600000,1.590000,1.542746e+04,5.151325e+02,6.000000,1.000000,0.000000,0.162200,0.092300,0.193100,2.000000,4.000000,1.000000,2.000000
50%,212.950000,7544.250000,2999.050000,6.380000,6.003908e+04,2.138445e+03,13.000000,3.000000,0.000000,0.264100,0.173300,0.313650,3.000000,7.000000,3.000000,3.000000
75%,447.000000,13543.625000,11374.000000,25.190000,2.296360e+05,8.743985e+03,18.000000,4.000000,0.000000,0.388500,0.280400,0.454100,4.000000,9.000000,5.000000,3.000000
max,720.000000,21999.400000,500000.000000,2469.640000,5.000000e+07,3.645516e+06,24.000000,5.000000,237.000000,0.889700,0.847300,0.958000,4.000000,12.000000,6.000000,4.000000

In [13]:
# медиана задержек>0
df_delayed = df[df['delay_hours'] > 0]
overall_median = df_delayed['delay_hours'].median()
overall_median

np.float64(16.5)

In [12]:
# медиана задержек по перевозчикам (median delay by carrier)
carrier_medians = df_delayed.groupby('carrier')['delay_hours'].median().reset_index()
carrier_medians

         carrier  delay_hours
0        CMA_CGM        16.10
1          COSCO        15.30
2    DB_Schenker        17.15
3            DHL        15.80
4      Evergreen        17.70
5          FedEx        16.60
6            HMM        16.60
7    Hapag-Lloyd        16.50
8   Kuehne_Nagel        16.70
9            MSC        16.50
10        Maersk        16.80
11           ONE        15.95
12           UPS        16.05
13     Yang_Ming        17.20
14           ZIM        16.40

In [11]:
carrier_medians = carrier_medians.sort_values(by='delay_hours').reset_index(drop=True)
carrier_medians.columns = ['Перевозчик', 'Медианное опоздание (ч)']
print("Медианное опоздание по каждому перевозчику:")
print(carrier_medians)

Медианное опоздание по каждому перевозчику:
      Перевозчик  Медианное опоздание (ч)
0          COSCO                    15.30
1            DHL                    15.80
2            ONE                    15.95
3            UPS                    16.05
4        CMA_CGM                    16.10
5            ZIM                    16.40
6            MSC                    16.50
7    Hapag-Lloyd                    16.50
8          FedEx                    16.60
9            HMM                    16.60
10  Kuehne_Nagel                    16.70
11        Maersk                    16.80
12   DB_Schenker                    17.15
13     Yang_Ming                    17.20
14     Evergreen                    17.70